version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mi_base_datos
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iris_db
      MYSQL_USER: iris_user
      MYSQL_PASSWORD: iris_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: ./app
    container_name: api_pred
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=iris_user
      - MYSQL_PASSWORD=iris_password
      - MYSQL_DATABASE=iris_db
      - ENV=developer
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
