# Usa una imagen base oficial de Python
FROM python:3.8-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de requerimientos y los instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Instala MySQL y otras utilidades
RUN apt-get update && apt-get install -y \
    mysql-server \
    && rm -rf /var/lib/apt/lists/*

# Copia el código fuente de la aplicación dentro del contenedor
COPY . .

# Variables de entorno para conectar con MySQL
ENV MYSQL_DATABASE=iris_db
ENV MYSQL_USER=iris_user
ENV MYSQL_PASSWORD=iris_pass
ENV MYSQL_ROOT_PASSWORD=rootpass
ENV ENVIRONMENT=developer

# Comando para iniciar MySQL y luego ejecutar un script de Python que prepara la base de datos
CMD service mysql start && python prepare_db.py && tail -f /dev/null